# Generated by Django 5.0.1 on 2024-01-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна производитель'),
        ),
    ]
